### ISSUE TITLE
Additional cursor data

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#17] opened 2018-08-22 17:05 UTC
Would love to be able to query
/world/cursor/force  

Perhaps cursor isn't exactly the right object, but accessing the force being applied back to the device could be musically quite useful. 

cursor/velocity and cursor/acceleration could also be of interest (rather than using a relatively inefficient client to calculate those)

I assume Chai could give us these fairly easily (?)

**Comment by bbattey** [comment] 2018-08-22 17:17
The comment in the documentation that 'The cursor has most of the same parameters as other objects in DIMPLE' made me think it might be possible to access these already, but get world/cursor/cursor/velocity 20  and similar did not work.

**Comment by radarsat1** [comment] 2018-08-22 18:22
I agree this should work.  It's the intended behaviour.  Marked as bug.

**Comment by radarsat1** [comment] 2019-02-21 17:26
Fixed in 055aa2dcf97739153c58e84409401bf8a4444cc8

**Closed as completed by radarsat1** 2019-02-21 17:26 UTC
Labels: bug
