### ISSUE TITLE
velocity/magnitude returning 0

### ISSUE THREAD

**Issue by bbattey** [radarsat1/dimple#8] opened 2018-04-17 14:43 UTC
test.pd / snake
---

/world/sn[x]/velocity/magnitude/get   100 is resulting in matching messages coming back from DIMPLE, but the value   consistently reads 0. regardless of the motion of the prisms. 

On the other   hand /world/sn1/velocity/get 100 works, returning the 3-number magnitude

**Comment by radarsat1** [comment] 2018-08-04 10:10
Duplicate of #7?

**Comment by bbattey** [comment] 2018-08-04 13:52
Slightly different, I think. In #7, no data is returned. In this example, data is returned, but it is always 0.

**Comment by radarsat1** [comment] 2019-02-21 17:36
Fixed in 3590da54770da3273e9af766a1f30b418a9124e6

**Closed as completed by radarsat1** 2019-02-21 17:36 UTC
Labels: bug
